### ISSUE TITLE
 Websockets fails to establish connection error 1006; accept failed: Invalid argument

### ISSUE THREAD

**Issue by ghost** [nanocurrency/nano-node#2818]
Does this issue reproduce with the latest release? if you don't use the latest version then please try our latest version.
Yes v20

Briefly describe the problem you are having in a few paragraphs. 

From log:
[2020-Jun-16 16:54:35.183405]: Websocket: listen failed: bind: Cannot assign requested address
[2020-Jun-16 16:54:35.347683]: Websocket: accept failed: Invalid argument

Websockets fails to establish connection error 1006
client ! failing CONNECTING WebSocket connection with code 1006

**Steps to reproduce the issue:**
1. launch docker nano node with websockets enabled
2. copy websockets sample python file https://github.com/guilhermelawless/nano-websocket-sample-py
3. run python file

**Describe the results you received:**
Websocket fails to connect with 1006 error.

```

client - state = CONNECTING
client - event = connection_made(<_SelectorSocketTransport fd=6 read=idle write=<idle, bufsize=0>>)
client > GET / HTTP/1.1
client > Headers([('Host', '::1:7078'), ('Upgrade', 'websocket'), ('Connection', 'Upgrade'), ('Sec-WebSocket-Key', 'lbwTU62b6jUSRV9CtL89/Q=='), ('Sec-WebSocket-Version', '13'), ('Sec-WebSocket-Extensions', 'permessage-deflate; client_max_window_bits'), ('User-Agent', 'Python/3.8 websockets/8.1')])
client - event = eof_received()
client ! failing CONNECTING WebSocket connection with code 1006
client - event = connection_lost(None)
client - state = CLOSED
client x code = 1006, reason = [no reason]
client x half-closing TCP connection
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/http.py", line 139, in read_response
    status_line = await read_line(stream)
  File "/usr/local/lib/python3.8/dist-packages/websockets/http.py", line 219, in read_line
    raise EOFError("line without CRLF")
EOFError: line without CRLF

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/websockets/client.py", line 101, in read_http_response
    status_code, reason, headers = await read_response(self.reader)
  File "/usr/local/lib/python3.8/dist-packages/websockets/http.py", line 141, in read_response
    raise EOFError("connection closed while reading HTTP status line") from exc
EOFError: connection closed while reading HTTP status line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "client.py", line 56, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "client.py", line 31, in main
    async with await websockets.connect(f"ws://{args.host}:{args.port}") as websocket:
  File "/usr/local/lib/python3.8/dist-packages/websockets/client.py", line 542, in __await_impl__
    await protocol.handshake(
  File "/usr/local/lib/python3.8/dist-packages/websockets/client.py", line 290, in handshake
    status_code, response_headers = await self.read_http_response()
  File "/usr/local/lib/python3.8/dist-packages/websockets/client.py", line 103, in read_http_response
    raise InvalidMessage("did not receive a valid HTTP response") from exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP response

```
Port info
```

Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 127.0.0.1:39657         0.0.0.0:*               LISTEN      738/containerd      
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN      593/systemd-resolve 
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      760/sshd: /usr/sbin 
tcp6       0      0 :::22                   :::*                    LISTEN      760/sshd: /usr/sbin 
tcp6       0      0 :::7075                 :::*                    LISTEN      3828/docker-proxy   
tcp6       0      0 ::1:7076                :::*                    LISTEN      3814/docker-proxy   
tcp6       0      0 ::1:7078                :::*                    LISTEN      3808/docker-proxy   
udp        0      0 127.0.0.53:53           0.0.0.0:*                           593/systemd-resolve 
udp6       0      0 :::7075                 :::*                                3841/docker-proxy   


```
**Describe the results you expected:**
Active websockets connection

**Additional information you deem important (e.g. issue happens only occasionally):**
N/A

**Environment**:

- OS information  
ubuntu 20.04
python 3.8
- (Linux) Kernel (e.g. `uname -a`): 5.4.0-37-generic #41-Ubuntu SMP Wed Jun 3 18:57:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Node version 20
- (docker node) docker version 

**logs**
```
[2020-Jun-16 16:54:34.285719]: Wallet unlocked
[2020-Jun-16 16:54:34.541352]: Wallet unlocked
[2020-Jun-16 16:54:34.748165]: Wallet unlocked
[2020-Jun-16 16:54:34.973807]: Wallet unlocked
[2020-Jun-16 16:54:35.181476]: Wallet unlocked
[2020-Jun-16 16:54:35.183405]: Websocket: listen failed: bind: Cannot assign requested address
[2020-Jun-16 16:54:35.183540]: Node starting, version: V20.0
[2020-Jun-16 16:54:35.183599]: Build information: a3ae21c "GNU C++ version " "5.4.0 20160609" "BOOST 106700" BUILT "Nov 12 2019"
[2020-Jun-16 16:54:35.183673]: Active network: live
[2020-Jun-16 16:54:35.183727]: Work pool running 2 threads
[2020-Jun-16 16:54:35.183778]: 0 work peers configured
[2020-Jun-16 16:54:35.183858]: Outbound Voting Bandwidth limited to 5242880 bytes per second
[2020-Jun-16 16:54:35.184508]: Node ID: node_33eo1naugdgsc8bse1cunn73sxrjro4wzm8wqw6ymotrf89qg5gj97heqz9s
[2020-Jun-16 16:54:35.184614]: Dropping unchecked blocks
[2020-Jun-16 16:54:35.262992]: Starting bootstrap attempt
[2020-Jun-16 16:54:35.263803]: Bootstrap stopped because there are no peers
[2020-Jun-16 16:54:35.264441]: Exiting bootstrap attempt
[2020-Jun-16 16:54:35.337162]: Beginning pending block search
[2020-Jun-16 16:54:35.344231]: Pending block search phase complete
[2020-Jun-16 16:54:35.344784]: IPC: server started
[2020-Jun-16 16:54:35.347683]: Websocket: accept failed: Invalid argument

``

**Comment by ghost** [comment]
config-node.toml
```
[node.websocket]

# WebSocket server bind address.
# type:string,ip
address = "::1"

# Enable or disable WebSocket server.
# type:bool
enable = true

# WebSocket server listening port.
# type:uint16
port = 7078

[rpc]

# Enable or disable RPC
# type:bool
enable = true

[node]
enable_voting = true

```

**Comment by ghost** [comment]
Perhaps related to #407

**Comment by zhyatt** [comment]
@0xaaroncrenshaw I think this need to be set:

```
# WebSocket server bind address.
# type:string,ip
address = "::ffff:0.0.0.0"
```

@argakiig Can you confirm? If so, do we need documentation updates for this? I think another case of this came up recently and a related PR changed this for V21 by default.

**Comment by ghost** [comment]
> @0xaaroncrenshaw I think this need to be set:
> 
> ```
> # WebSocket server bind address.
> # type:string,ip
> address = "::ffff:0.0.0.0"
> ```
> 
> @argakiig Can you confirm? If so, do we need documentation updates for this? I think another case of this came up recently and a related PR changed this for V21 by default.

Just changed that. It is working now! Documentation on the Websockets page would be helpful I think.

**Comment by ghost** [comment]
I made a test ping code here for anyone else debugging. It seems the issue is solved.
```
import websocket
import logging
import json

logger = logging.getLogger('websockets')
logger.setLevel(logging.INFO)
logger.addHandler(logging.StreamHandler())
try:
    import thread
except ImportError:
    import _thread as thread
import time

def on_message(ws, message):
    print(message)

def on_error(ws, error):
    print(error)

def on_close(ws):
    print("### closed ###")

def on_open(ws):
    def run(*args):
        for i in range(3):
            time.sleep(1)
            ws.send(json.dumps({"action":"ping"}))
        time.sleep(1)
        ws.close()
        print("thread terminating...")
    thread.start_new_thread(run, ())


if __name__ == "__main__":
    websocket.enableTrace(True)
    ws = websocket.WebSocketApp("ws://[::1]:7078/",
                              on_message = on_message,
                              on_error = on_error,
                              on_close = on_close)
    ws.on_open = on_open
    ws.run_forever()
```
response
```
--- request header ---
GET / HTTP/1.1
Upgrade: websocket
Host: [::1]:7078
Origin: http://[::1]:7078
Sec-WebSocket-Key: hoCFVxyrhKD0lRRaG4az7g==
Sec-WebSocket-Version: 13
Connection: upgrade


-----------------------
--- response header ---
HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: upgrade
Sec-WebSocket-Accept: jNqWecu63oRvM+gJQIFtlgqJYSE=
Server: Boost.Beast/167
-----------------------
send: b'\x81\x92\xef\xf3\xa0\xc1\x94\xd1\xc1\xa2\x9b\x9a\xcf\xaf\xcd\xc9\x80\xe3\x9f\x9a\xce\xa6\xcd\x8e'
{
    "ack": "pong",
    "time": "1592328669282"
}

send: b'\x81\x929\x8fl\xf6B\xad\r\x95M\xe6\x03\x98\x1b\xb5L\xd4I\xe6\x02\x91\x1b\xf2'
{
    "ack": "pong",
    "time": "1592328670284"
}

send: b'\x81\x92\xe5\x04\xe1\xa2\x9e&\x80\xc1\x91m\x8e\xcc\xc7>\xc1\x80\x95m\x8f\xc5\xc7y'
{
    "ack": "pong",
    "time": "1592328671286"
}

send: b'\x88\x82\xebS\xc2u\xe8\xbb'
### closed ###
```

**Comment by zhyatt** [comment]
Glad you resolved. Added ticket for getting docs updated.
